[package]
edition = "2018"
name = "mio"
# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create git tag
version       = "0.7.2"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://docs.rs/mio/0.7.2"
homepage      = "https://github.com/tokio-rs/mio"
repository    = "https://github.com/tokio-rs/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
include       = [
  "Cargo.toml",
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
  "src/**/*.rs",
  "examples/**/*.rs",
]
publish = false

[features]
default = []
os-poll = []
os-util = []
tcp = []
udp = []
uds = []
extra-docs = []

[dependencies]
log = "0.4.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2.69"

[target.'cfg(windows)'.dependencies]
miow   = "0.3.3"
winapi = { version = "0.3", features = ["winsock2", "mswsock"] }
ntapi  = "0.3"

[target.x86_64-fortanix-unknown-sgx.dependencies]
async-usercalls = { git = "https://github.com/fortanix/rust-sgx.git", branch = "mz/async-usercalls" } # FIXME: use published version once available
crossbeam-channel = "0.4"

[dev-dependencies]
env_logger = { version = "0.6.2", default-features = false }
rand = "0.4"

[target.'cfg(unix)'.dev-dependencies]
net2 = "0.2.33"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
features = ["os-poll", "os-util", "tcp", "udp", "uds"]

[[example]]
name = "tcp_server"
required-features = ["os-poll", "tcp"]

[[example]]
name = "udp_server"
required-features = ["os-poll", "udp"]

# set number of threads so tests can run properly
[package.metadata.fortanix-sgx]
threads=100
